/**
 * Hebrew text constants for the application
 * All text content is in Hebrew to match the website
 */

export const hebrewTexts = {
  // Authentication
  auth: {
    login: 'התחברות',
    username: 'שם משתמש',
    password: 'סיסמה',
    loginButton: 'התחבר',
    loginFailed: 'שגיאה בהתחברות',
    invalidCredentials: 'שם משתמש או סיסמה שגויים',
    connectionError: 'שגיאת חיבור לשרת',
    logout: 'התנתק',
    logoutConfirm: 'האם אתה בטוח שברצונך להתנתק?',
    cancel: 'ביטול',
    confirm: 'אישור',
    passwordChange: 'שינוי סיסמה',
    currentPassword: 'סיסמה נוכחית',
    newPassword: 'סיסמה חדשה',
    confirmPassword: 'אישור סיסמה',
    passwordsNotMatch: 'הסיסמאות אינן תואמות',
    passwordChanged: 'הסיסמה שונתה בהצלחה',
    passwordChangeRequired: 'נדרש שינוי סיסמה',
  },

  // Navigation
  navigation: {
    dashboard: 'לוח בקרה',
    events: 'אירועים',
    actionReports: 'דוחות פעולה',
    profile: 'פרופיל',
    users: 'משתמשים',
    settings: 'הגדרות',
    vehicles: 'רכבים',
    volunteers: 'מתנדבים',
    statistics: 'סטטיסטיקות',
  },

  // Dashboard
  dashboard: {
    welcome: 'ברוך הבא',
    welcomeBack: 'ברוך השב',
    availability: 'זמינות',
    available: 'זמין',
    unavailable: 'לא זמין',
    toggleAvailability: 'שנה זמינות',
    recentEvents: 'אירועים אחרונים',
    noEvents: 'אין אירועים',
    statistics: 'סטטיסטיקות',
    totalEvents: 'סה"כ אירועים',
    activeEvents: 'אירועים פעילים',
    resolvedEvents: 'אירועים סגורים',
    availableVolunteers: 'מתנדבים זמינים',
    refresh: 'רענן',
    lastUpdate: 'עדכון אחרון',
    now: 'עכשיו',
    minutesAgo: 'דקות קודם',
    hoursAgo: 'שעות קודם',
    daysAgo: 'ימים קודם',
  },

  // Events
  events: {
    title: 'אירועים',
    newEvent: 'אירוע חדש',
    eventDetails: 'פרטי אירוע',
    status: 'סטטוס',
    priority: 'עדיפות',
    location: 'מיקום',
    description: 'תיאור',
    assignedTo: 'הוקצה ל',
    createdAt: 'נוצר ב',
    updatedAt: 'עודכן ב',
    reportedBy: 'דווח על ידי',
    vehicle: 'רכב',
    licenseNumber: 'מספר רישוי',
    color: 'צבע',
    model: 'דגם',
    manufacturer: 'יצרן',
    year: 'שנה',
    
    // Event statuses
    statuses: {
      new: 'חדש',
      assigned: 'הוקצה',
      in_progress: 'בטיפול',
      resolved: 'נפתר',
      closed: 'סגור',
      cancelled: 'בוטל',
    },

    // Event priorities
    priorities: {
      low: 'נמוכה',
      medium: 'בינונית',
      high: 'גבוהה',
      urgent: 'דחוף',
    },

    // Actions
    assign: 'הקצה',
    unassign: 'בטל הקצאה',
    updateStatus: 'עדכן סטטוס',
    addNote: 'הוסף הערה',
    viewMap: 'הצג במפה',
    call: 'התקשר',
    navigate: 'נווט',
    share: 'שתף',
    print: 'הדפס',
    export: 'ייצא',
  },

  // Action Reports
  actionReports: {
    title: 'דוחות פעולה',
    newReport: 'דוח חדש',
    reportDetails: 'פרטי דוח',
    eventId: 'מספר אירוע',
    actionTaken: 'פעולה שננקטה',
    outcome: 'תוצאה',
    notes: 'הערות',
    photos: 'תמונות',
    addPhoto: 'הוסף תמונה',
    takePhoto: 'צלם',
    selectFromGallery: 'בחר מהגלריה',
    save: 'שמור',
    submit: 'שלח',
    draft: 'טיוטה',
    submitted: 'נשלח',
    approved: 'אושר',
    rejected: 'נדחה',
  },

  // Profile
  profile: {
    title: 'פרופיל',
    personalInfo: 'מידע אישי',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    email: 'אימייל',
    phone: 'טלפון',
    role: 'תפקיד',
    department: 'מחלקה',
    profilePhoto: 'תמונת פרופיל',
    changePhoto: 'שנה תמונה',
    preferences: 'העדפות',
    notifications: 'התראות',
    language: 'שפה',
    theme: 'נושא',
    privacy: 'פרטיות',
    security: 'אבטחה',
    changePassword: 'שנה סיסמה',
    twoFactor: 'אימות דו-שלבי',
    loginHistory: 'היסטוריית התחברות',
    updateProfile: 'עדכן פרופיל',
    profileUpdated: 'הפרופיל עודכן בהצלחה',
  },

  // Users (Admin only)
  users: {
    title: 'משתמשים',
    newUser: 'משתמש חדש',
    userDetails: 'פרטי משתמש',
    active: 'פעיל',
    inactive: 'לא פעיל',
    suspended: 'מושעה',
    roles: {
      admin: 'מנהל',
      sayer: 'סייר',
      volunteer: 'מתנדב',
      dispatcher: 'מוקדן',
      supervisor: 'מפקח',
    },
    permissions: 'הרשאות',
    lastLogin: 'התחברות אחרונה',
    createdAt: 'נוצר ב',
    edit: 'ערוך',
    delete: 'מחק',
    activate: 'הפעל',
    deactivate: 'בטל הפעלה',
    resetPassword: 'איפוס סיסמה',
    sendInvitation: 'שלח הזמנה',
  },

  // Settings
  settings: {
    title: 'הגדרות',
    general: 'כללי',
    notifications: 'התראות',
    privacy: 'פרטיות',
    security: 'אבטחה',
    about: 'אודות',
    version: 'גרסה',
    build: 'בנייה',
    checkUpdates: 'בדוק עדכונים',
    help: 'עזרה',
    support: 'תמיכה',
    feedback: 'משוב',
    terms: 'תנאי שימוש',
    privacyPolicy: 'מדיניות פרטיות',
    logout: 'התנתק',
    
    // Notification settings
    pushNotifications: 'התראות דחיפה',
    emailNotifications: 'התראות אימייל',
    smsNotifications: 'התראות SMS',
    eventAlerts: 'התראות אירועים',
    systemAlerts: 'התראות מערכת',
    maintenanceAlerts: 'התראות תחזוקה',
    sound: 'צליל',
    vibration: 'רטט',
    quietHours: 'שעות שקט',
    from: 'מ',
    to: 'עד',
  },

  // Common
  common: {
    yes: 'כן',
    no: 'לא',
    ok: 'אישור',
    cancel: 'ביטול',
    save: 'שמור',
    delete: 'מחק',
    edit: 'ערוך',
    view: 'הצג',
    add: 'הוסף',
    remove: 'הסר',
    update: 'עדכן',
    refresh: 'רענן',
    loading: 'טוען...',
    error: 'שגיאה',
    success: 'הצלחה',
    warning: 'אזהרה',
    info: 'מידע',
    search: 'חיפוש',
    filter: 'סנן',
    sort: 'מיין',
    export: 'ייצא',
    import: 'ייבא',
    print: 'הדפס',
    share: 'שתף',
    copy: 'העתק',
    paste: 'הדבק',
    cut: 'גזור',
    undo: 'בטל',
    redo: 'חזור',
    select: 'בחר',
    selectAll: 'בחר הכל',
    clear: 'נקה',
    reset: 'איפוס',
    apply: 'החל',
    submit: 'שלח',
    send: 'שלח',
    receive: 'קבל',
    upload: 'העלה',
    download: 'הורד',
    open: 'פתח',
    close: 'סגור',
    next: 'הבא',
    previous: 'הקודם',
    first: 'ראשון',
    last: 'אחרון',
    page: 'עמוד',
    of: 'מתוך',
    total: 'סה"כ',
    items: 'פריטים',
    selected: 'נבחר',
    all: 'הכל',
    none: 'ללא',
    empty: 'ריק',
    noData: 'אין נתונים',
    noResults: 'אין תוצאות',
    notFound: 'לא נמצא',
    required: 'חובה',
    optional: 'אופציונלי',
    enabled: 'מופעל',
    disabled: 'מבוטל',
    online: 'מחובר',
    offline: 'לא מחובר',
    connected: 'מחובר',
    disconnected: 'מנותק',
    syncing: 'מסנכרן',
    synced: 'מסונכרן',
    pending: 'ממתין',
    processing: 'מעבד',
    completed: 'הושלם',
    failed: 'נכשל',
    retry: 'נסה שוב',
    timeout: 'פג הזמן',
    today: 'היום',
    yesterday: 'אתמול',
    tomorrow: 'מחר',
    thisWeek: 'השבוע',
    thisMonth: 'החודש',
    thisYear: 'השנה',
    minute: 'דקה',
    minutes: 'דקות',
    hour: 'שעה',
    hours: 'שעות',
    day: 'יום',
    days: 'ימים',
    week: 'שבוע',
    weeks: 'שבועות',
    month: 'חודש',
    months: 'חודשים',
    year: 'שנה',
    years: 'שנים',
    am: 'לפנה"צ',
    pm: 'אחה"צ',
  },

  // Error messages
  errors: {
    network: 'שגיאת רשת - בדוק את החיבור לאינטרנט',
    server: 'שגיאת שרת - נסה שוב מאוחר יותר',
    unauthorized: 'אין הרשאה - התחבר מחדש',
    forbidden: 'אין הרשאה לפעולה זו',
    notFound: 'הפריט לא נמצא',
    validation: 'שגיאת אימות נתונים',
    required: 'שדה זה הוא חובה',
    invalidEmail: 'כתובת אימייל לא תקינה',
    invalidPhone: 'מספר טלפון לא תקין',
    passwordTooShort: 'הסיסמה קצרה מדי',
    passwordTooWeak: 'הסיסמה חלשה מדי',
    fileTooBig: 'הקובץ גדול מדי',
    fileTypeNotSupported: 'סוג קובץ לא נתמך',
    locationPermissionDenied: 'הרשאת מיקום נדחתה',
    cameraPermissionDenied: 'הרשאת מצלמה נדחתה',
    storagePermissionDenied: 'הרשאת אחסון נדחתה',
    notificationPermissionDenied: 'הרשאת התראות נדחתה',
    unknown: 'שגיאה לא ידועה',
  },

  // Success messages
  success: {
    saved: 'נשמר בהצלחה',
    updated: 'עודכן בהצלחה',
    deleted: 'נמחק בהצלחה',
    sent: 'נשלח בהצלחה',
    uploaded: 'הועלה בהצלחה',
    downloaded: 'הורד בהצלחה',
    copied: 'הועתק בהצלחה',
    synced: 'סונכרן בהצלחה',
    connected: 'חובר בהצלחה',
    loggedIn: 'התחברת בהצלחה',
    loggedOut: 'התנתקת בהצלחה',
  },
};
